### ISSUE TITLE
Version >=1.0.0 fails for users with an accent in their name

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#816]
Users with certain accents in their name (at least for é) can not use the notebook server as decoding the jwt in the notebook server will fail with this error:

```
[2021-11-22 16:05:54,468] ERROR in app: Exception on /notebooks/servers [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_apispec/annotations.py", line 122, in wrapped
    return wrapper(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_apispec/wrapper.py", line 29, in __call__
    response = self.call_view(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_apispec/wrapper.py", line 52, in call_view
    return self.func(*args, **kwargs)
  File "/renku-notebooks/renku_notebooks/api/auth.py", line 41, in decorated
    registered_user = RegisteredUser(request.headers)
  File "/renku-notebooks/renku_notebooks/api/classes/user.py", line 87, in __init__
    parsed_id_token = self.parse_jwt_from_headers(headers)
  File "/renku-notebooks/renku_notebooks/api/classes/user.py", line 118, in parse_jwt_from_headers
    return json.loads(base64.b64decode(jwt.split(".")[1].encode() + b"=="))
  File "/usr/local/lib/python3.7/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 365: invalid continuation byte
```

**Comment by olevski** [comment]
Oh that sucks. I can't even figure out how to make an email or even a gitlab/renku account with that name - gitlab does not allow those characters and it seems you cannot have an email with those characters either. I guess I will update my account directly in keycloak.
